"""initial migration

Revision ID: d9851f955a38
Revises: 
Create Date: 2024-08-08 12:44:51.584048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd9851f955a38'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journals')
    op.drop_table('entries')
    op.drop_index('email', table_name='users')
    op.drop_table('users')
    op.drop_table('photos')
    op.drop_index('api_key', table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('device_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('device_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('device_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('os_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('os_version', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('app_version', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('last_sync', mysql.DATETIME(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('api_key', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('time_created', mysql.DATETIME(), nullable=False),
    sa.Column('time_modified', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='devices_ibfk_1'),
    sa.PrimaryKeyConstraint('device_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('api_key', 'devices', ['api_key'], unique=True)
    op.create_table('photos',
    sa.Column('photo_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('journal_id', mysql.CHAR(length=32), nullable=True),
    sa.Column('device_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('time_created', mysql.DATETIME(), nullable=False),
    sa.Column('time_modified', mysql.DATETIME(), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.LONGTEXT(), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('starred', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('file_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('file_size', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_type', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], name='photos_ibfk_3'),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.journal_id'], name='photos_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='photos_ibfk_1'),
    sa.PrimaryKeyConstraint('photo_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('user_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('time_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_login', mysql.DATETIME(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('profile_picture_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('bio', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('email', 'users', ['email'], unique=True)
    op.create_table('entries',
    sa.Column('entry_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('journal_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('device_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('time_created', mysql.DATETIME(), nullable=False),
    sa.Column('time_modified', mysql.DATETIME(), nullable=False),
    sa.Column('position', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('content', mysql.LONGTEXT(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], name='entries_ibfk_3'),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.journal_id'], name='entries_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='entries_ibfk_1'),
    sa.PrimaryKeyConstraint('entry_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('journals',
    sa.Column('journal_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=32), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.LONGTEXT(), nullable=True),
    sa.Column('time_created', mysql.DATETIME(), nullable=False),
    sa.Column('time_modified', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='journals_ibfk_1'),
    sa.PrimaryKeyConstraint('journal_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
